dataset_config:
  dataset_filepath: /home/user/sources/unet/hdd/stage_3/dataset.csv
  test_folds:
    - 22_ph0
  validation_folds:
    - 26_ph1
  exclude_folds:
    - /home/user/sources/unet/hdd/exclude_folds/
  num_workers: 3
  batch_size: 60
  pin_memory: true


optimizer_config:
  optimizer_name: adam
  learning_rate: 0.003
  weight_decay: 0.0005

scheduler_config:
  milestones:
    - 15
    - 30
    - 35
    - 40
  gamma: 0.2

loss_config:
  loss_name: mse

output_config:
  out_folder: /home/user/sources/unet/hdd/first_launch

model_name: 'unet1d'

epochs_num: 3
save_step_size: 1
device: cpu